name: ðŸ“¦ Build Push Containers
run-name: Building containers for ${{ github.ref_name }}

on:   
  push:
    branches:
      - '**'
    tags:
      - '[0-9]*.[0-9]*.[0-9]*'

jobs:

  read-github-context-object:
    runs-on: ubuntu-latest
    steps:
      # I know this is not pretty (debug information) but it's useful to have this
    - name: Read github context
      env: 
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: |
        echo "GITHUB_SHA=${GITHUB_SHA}"
        echo "INFO: github context object content below"
        echo "${GITHUB_CONTEXT}"

#  build-push-checked-containers:
#    uses: ./.github/workflows/build-push-container.yml
#    name: Build Push Checked Containers
#    secrets: inherit
#    strategy:
#      matrix:
#        container_name:
   
#    with:
#      container_name: ${{ matrix.container_name }}

#  build-push-checked-manifest:
#    uses: ./.github/workflows/build-push-manifest.yml
#    name: Build Push Checked Manifest
#    needs: 
#      - build-push-checked-containers
#    secrets: inherit
#    strategy:
#      matrix:
#        container_name:
#    with:
#      container_name: ${{ matrix.container_name }}